name: KadePay CI

on:
  push:
    branches:
      - main
      - chores/ci-tests-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    needs:
      - unit
      - e2e
    uses: ./.github/workflows/build.yml

  unit:
    uses: ./.github/workflows/unit.yml

  e2e:
    uses: ./.github/workflows/e2e.yml